# Generated by Django 5.0.1 on 2024-02-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhrasalVerbs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrasal_verb', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=80)),
                ('example', models.CharField(max_length=120, null=True)),
            ],
        ),
    ]
